POST /api/login
content-type: application/json
Host: 127.0.0.1:4000

{
    "user":{

      "email": "userone@gmail.com",
      "password": "userone@gmail.com"
    }

    
}

###
GET /api/admin/partners
content-type: application/json
Host: 127.0.0.1:4000
Authorization: SFMyNTY.ZmFjMTJlN2QtY2Y4Ny00N2QyLWIzYjktOTFjZjA1NDU4MjI4.BHh3NPSiifnPg8N8Ut4obJ4sTuZa9qNEDWKM0HZ7AaE



###Admin
### Add Partner
POST /api/admin/partners/new
content-type: application/json
Host: 127.0.0.1:4000

{
  "partner": {
    "name":"API Test API",
    "phone":"254741287654",
    "location":"Mugumoinias",
    "contact_email":"user@retailer.com",
    "lat": "-1.268870",
    "lng": "36.785554",
    "type": "retailer",
    "user": {
            "first_name":"API",
            "second_name":"Test",
            "phone": "254741287654",
            "email": "apitest@gmail.com",
            "role": "retailer_admin",
            "password": "apitest@gmail.com",
            "confirm_password": "apitest@gmail.com"
    }
  }
}

### Show Partner
GET  /api/admin/partners/1
content-type: application/json
Host: 127.0.0.1:4000

### Update Partner
POST /api/admin/partners/2/edit
content-type: application/json
Host: 127.0.0.1:4000

{
  "partner": {
    "name":"Updated Through API",
    "phone":"254712983876",
    "location":"Madaraka Estate",
    "contact_email":"retailer@user.com",
    "lat": -1.268870,
    "lng": 36.785554,
    "type": "retailer"
  }
}

### Delete Partner
DELETE  /api/admin/partners/3
content-type: application/json
Host: 127.0.0.1:4000

### Show Products

### Add Product

### Update Product

### Delete Product

### Add Warehouse

### Update Warehouse

### Delete Warehouse


###Retailer
### Add Order

### Update Order

### Delete Order

### Update OrderDetails

### Delete OrderDetails

###Supplier
### Add Product

### Update Product

### Delete Product





