POST /api/login
content-type: application/json
Host: 127.0.0.1:4000

{
    "user":{

      "email": "userone@gmail.com",
      "password": "userone@gmail.com"
    }

    
}

###
GET /api/admin/partners
content-type: application/json
Host: 127.0.0.1:4000
Authorization: SFMyNTY.ZmFjMTJlN2QtY2Y4Ny00N2QyLWIzYjktOTFjZjA1NDU4MjI4.BHh3NPSiifnPg8N8Ut4obJ4sTuZa9qNEDWKM0HZ7AaE

### Add Product

### Update Product

### Delete Product

### Add Warehouse

### Update Warehouse

### Delete Warehouse

### Add Partner
GET /api/admin/partner/new
content-type: application/json
Host: 127.0.0.1:4000

{
  "partner": {
    "name":"",
    "phone":"",
    "location":"",
    "contact_emali","",
    "lat": "",
    "lng": "",
    "type": ""
    "user":{
      "first_name":"",
            "second_name":"",
            "phone": "",
            "email": "",
            "role":"",
            "password_hash"":"""

    }
  }
}

### Update Partner

### Delete Partner

### Add Order

### Update Order

### Delete Order

### Update OrderDetails

### Delete OrderDetails





