// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOKk75RKbKk33OBMRA7_spGV6xJLGFWdk',
    appId: '1:876173292998:web:6d37378c29ec518510eec7',
    messagingSenderId: '876173292998',
    projectId: 'kefis-437a5',
    authDomain: 'kefis-437a5.firebaseapp.com',
    storageBucket: 'kefis-437a5.appspot.com',
    measurementId: 'G-VJCXEN81C9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQjZRv4EsfmSt8WvTeI98a2xreucxeQRY',
    appId: '1:876173292998:android:f6106ca1cb96487e10eec7',
    messagingSenderId: '876173292998',
    projectId: 'kefis-437a5',
    storageBucket: 'kefis-437a5.appspot.com',
  );
}
